# -*- mode: ruby -*-
# vi: set ft=ruby :
variableWeb1 = "/vagrant/web1/index.html"
variableWeb2 = "/vagrant/web2/index.html"
Vagrant.configure("2") do |config|

    if Vagrant.has_plugin? "vagrant-vbguest"
      config.vbguest.no_install  = true
      config.vbguest.auto_update = false
      config.vbguest.no_remote   = true
    end

    config.vm.define :servidorUbuntu1 do |servidorUbuntu1|
      servidorUbuntu1.vm.box = "bento/ubuntu-20.04"
      servidorUbuntu1.vm.network :private_network, ip: "192.168.100.5"
      servidorUbuntu1.vm.hostname = "servidorUbuntu1"
      servidorUbuntu1.vm.provision "shell", path: "script.sh", "args" => [variableWeb1]
    end

    config.vm.define :servidorUbuntu2 do |servidorUbuntu2|
      servidorUbuntu2.vm.box = "bento/ubuntu-20.04"
      servidorUbuntu2.vm.network :private_network, ip: "192.168.100.4"
      servidorUbuntu2.vm.hostname = "servidorUbuntu2"
      servidorUbuntu2.vm.provision "shell", path: "script.sh", "args" => [variableWeb2]
    end

    config.vm.define :servidorUbuntuProxy do |servidorUbuntuProxy|
      servidorUbuntuProxy.vm.box = "bento/ubuntu-20.04"
      servidorUbuntuProxy.vm.network :private_network, ip: "192.168.100.6"
      servidorUbuntuProxy.vm.hostname = "servidorUbuntuProxy"
      servidorUbuntuProxy.vm.provision "shell", path: "script_haproxy.sh"
    end    
  end