# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :servidorUbuntuLXD do |servidorUbuntuLXD|
    servidorUbuntuLXD.vm.box = "bento/ubuntu-20.04"
    servidorUbuntuLXD.vm.network :private_network, ip: "192.168.100.4"
    servidorUbuntuLXD.vm.hostname = "servidorUbuntuLXD"
    servidorUbuntuLXD.vm.provision "shell", path: "script.sh"
  end
end