apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook-deployment
spec:
  selector:
    matchLabels:
      app: jupyter-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
     containers:
     - name: jupyter-notebook
       image: jupyter/datascience-notebook
       imagePullPolicy: Always
       ports:
       - containerPort: 8888