# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    if Vagrant.has_plugin? "vagrant-vbguest"
        config.vbguest.no_install  = true
        config.vbguest.auto_update = false
        config.vbguest.no_remote   = true
    end

    config.vm.define :servidorKub do |servidorKub|
        servidorKub.vm.box = "bento/ubuntu-20.04"
        servidorKub.vm.network :private_network, ip: "192.168.100.3"
        servidorKub.vm.hostname = "servidorKub"
        servidorKub.vm.provider "virtualbox" do |v|
            v.cpus = 2
            v.memory = 3072
        end
        servidorKub.vm.provision "shell", path: "scriptDocker.sh"
      end
    end